[//]: # remote_theme: pages-themes/minimal@v0.2.0
[//]: # remote_theme: pages-themes/cayman@v0.2.0
[//]: # remote_theme: pages-themes/dinky@v0.2.0
[//]: # remote_theme: pages-themes/modernist@v0.2.0
title: [<span style="color: #81AAD1; font-family: Corbel Light;">Смотреть презентацию</span>]
[//]: # title: [<img src="./аллергия обложка.png" alt="logo" />]

[//]: # title: [<span style="color: #0000ff;">Патофизиология</span>]


